### ISSUE TITLE
解锁网易云音乐 | Lolico's Blog

### ISSUE THREAD

**Issue by LOLICOL1** [LOLICOL1/lolicol1.github.io#22]
https://lolico.me/2020/03/23/unblock-netease-music/

**Comment by JohnnRen** [comment]
十分感谢qq！

**Comment by miracle1103** [comment]
大佬我直接用了你的配置，发现网易云是成功解锁了，但是发现fq节点用不了了，是怎么回事啊？

**Comment by LOLICOL1** [comment]
> @miracle1103
> 大佬我直接用了你的配置，发现网易云是成功解锁了，但是发现fq节点用不了了，是怎么回事啊？

如果你是直接导入了配置文件，那么相当于用了一个新的配置，而这个配置是没有科学上网的节点的，所以也就不存说可以fq了，如果你用的是clash并且能折腾可以去用转换api自己写分流然后合并两个订阅，如果不能，那就在不听网易时换回平时的配置，如果用的其他代理软件 比较好添加节点 也可以手动添加节点和分流策略

**Comment by miracle1103** [comment]
> > @miracle1103
> > 大佬我直接用了你的配置，发现网易云是成功解锁了，但是发现fq节点用不了了，是怎么回事啊？
> 
> 如果你是直接导入了配置文件，那么相当于用了一个新的配置，而这个配置是没有科学上网的节点的，所以也就不存说可以fq了，如果你用的是clash并且能折腾可以去用转换api自己写分流然后合并两个订阅，如果不能，那就在不听网易时换回平时的配置，如果用的其他代理软件，比较好添加节点订阅和分流订阅，也可以手动添加节点和分流订阅。

嗯嗯，谢谢大佬解惑！我用的iphone的quantumultx代理工具，我是有从机场购买的节点订阅的，不能fq可能是因为我没有设置策略组分流，也没有添加远程的分流订阅，所以肯定是不能科学上网了。感谢大佬热心解答！~

**Comment by LOLICOL1** [comment]
> @miracle1103
> 
> 
> 
> 
> > > @miracle1103
> > > 大佬我直接用了你的配置，发现网易云是成功解锁了，但是发现fq节点用不了了，是怎么回事啊？
> > 
> > 如果你是直接导入了配置文件，那么相当于用了一个新的配置，而这个配置是没有科学上网的节点的，所以也就不存说可以fq了，如果你用的是clash并且能折腾可以去用转换api自己写分流然后合并两个订阅，如果不能，那就在不听网易时换回平时的配置，如果用的其他代理软件，比较好添加节点订阅和分流订阅，也可以手动添加节点和分流订阅。
> 
> 嗯嗯，谢谢大佬解惑！我用的iphone的quantumultx代理工具，我是有从机场购买的节点订阅的，不能fq可能是因为我没有设置策略组分流，也没有添加远程的分流订阅，所以肯定是不能科学上网了。感谢大佬热心解答！~

用quanx可以参考文中iOS部分[quanx手动修改配置](https://lolico.me/2020/03/23/unblock-netease-music/#QuantumultX)这部分内容，自行修改配置，在自己原有配置的基础上再在对应板块添加给出的配置就行了

**Comment by miracle1103** [comment]
> > @miracle1103
> > > > @miracle1103
> > > > 大佬我直接用了你的配置，发现网易云是成功解锁了，但是发现fq节点用不了了，是怎么回事啊？
> > > 
> > > 
> > > 如果你是直接导入了配置文件，那么相当于用了一个新的配置，而这个配置是没有科学上网的节点的，所以也就不存说可以fq了，如果你用的是clash并且能折腾可以去用转换api自己写分流然后合并两个订阅，如果不能，那就在不听网易时换回平时的配置，如果用的其他代理软件，比较好添加节点订阅和分流订阅，也可以手动添加节点和分流订阅。
> > 
> > 
> > 嗯嗯，谢谢大佬解惑！我用的iphone的quantumultx代理工具，我是有从机场购买的节点订阅的，不能fq可能是因为我没有设置策略组分流，也没有添加远程的分流订阅，所以肯定是不能科学上网了。感谢大佬热心解答！~
> 
> 用quanx可以参考文中iOS部分[quanx手动修改配置](https://lolico.me/2020/03/23/unblock-netease-music/#QuantumultX)这部分内容，自行修改配置，在自己原有配置的基础上再在对应板块添加给出的配置就可以做到解锁的同时还不影响之前的使用

嗯嗯，大佬我已经手动添加上，并且使用大佬您的配置成功解锁网易云了，速度也很快！~但是经过我测试，发现大佬您的4个网易云解锁节点，1和4是可用的，2和3不可用，可能是2和3解锁节点失效了，不过不影响使用，还是万分感谢大佬！~最后还有一个问题想问下大佬，如果我直接使用您的qx配置文件，我应该就自己再不用生成证书了吧，直接点配置证书，配置好您的证书并信任是否就可以了？

**Comment by LOLICOL1** [comment]
> @miracle1103
> > > @miracle1103
> > > > > @miracle1103
> > > > > 大佬我直接用了你的配置，发现网易云是成功解锁了，但是发现fq节点用不了了，是怎么回事啊？
> > > > 
> > > > 
> > > > 如果你是直接导入了配置文件，那么相当于用了一个新的配置，而这个配置是没有科学上网的节点的，所以也就不存说可以fq了，如果你用的是clash并且能折腾可以去用转换api自己写分流然后合并两个订阅，如果不能，那就在不听网易时换回平时的配置，如果用的其他代理软件，比较好添加节点订阅和分流订阅，也可以手动添加节点和分流订阅。
> > > 
> > > 
> > > 嗯嗯，谢谢大佬解惑！我用的iphone的quantumultx代理工具，我是有从机场购买的节点订阅的，不能fq可能是因为我没有设置策略组分流，也没有添加远程的分流订阅，所以肯定是不能科学上网了。感谢大佬热心解答！~
> > 
> > 用quanx可以参考文中iOS部分[quanx手动修改配置](https://lolico.me/2020/03/23/unblock-netease-music/#QuantumultX)这部分内容，自行修改配置，在自己原有配置的基础上再在对应板块添加给出的配置就可以做到解锁的同时还不影响之前的使用
> 
> 嗯嗯，大佬我已经手动添加上，并且使用大佬您的配置成功解锁网易云了，速度也很快！~但是经过我测试，发现大佬您的4个网易云解锁节点，1和4是可用的，2和3不可用，可能是2和3解锁节点失效了，不过不影响使用，还是万分感谢大佬！~最后还有一个问题想问下大佬，如果我直接使用您的qx配置文件，我应该就自己再不用生成证书了吧，直接点配置证书，配置好您的证书并信任是否就可以了？

节点2我刚试了下是有用的，为什么你那里没用我不太清楚，是不是没有信任解锁网易云音乐的证书呢？，3比较慢而且时常抽风。另外，如果你有一套自己的quanx的配置，不建议用quanx方式一的全局配置文件，因为这个配置只有广告屏蔽和解锁网易云音乐的分流策略，当然，如果你自己在这个基础上另外加也可以。至于quanx中mitm的证书，你也可以用我全局配置中的那个证书。如果担心隐私和安全问题，你也可以在quanx中另外生成一个。

**Comment by miracle1103** [comment]
> > @miracle1103
> > > > @miracle1103
> > > > > > @miracle1103
> > > > > > 大佬我直接用了你的配置，发现网易云是成功解锁了，但是发现fq节点用不了了，是怎么回事啊？
> > > > > 
> > > > > 
> > > > > 如果你是直接导入了配置文件，那么相当于用了一个新的配置，而这个配置是没有科学上网的节点的，所以也就不存说可以fq了，如果你用的是clash并且能折腾可以去用转换api自己写分流然后合并两个订阅，如果不能，那就在不听网易时换回平时的配置，如果用的其他代理软件，比较好添加节点订阅和分流订阅，也可以手动添加节点和分流订阅。
> > > > 
> > > > 
> > > > 嗯嗯，谢谢大佬解惑！我用的iphone的quantumultx代理工具，我是有从机场购买的节点订阅的，不能fq可能是因为我没有设置策略组分流，也没有添加远程的分流订阅，所以肯定是不能科学上网了。感谢大佬热心解答！~
> > > 
> > > 
> > > 用quanx可以参考文中iOS部分[quanx手动修改配置](https://lolico.me/2020/03/23/unblock-netease-music/#QuantumultX)这部分内容，自行修改配置，在自己原有配置的基础上再在对应板块添加给出的配置就可以做到解锁的同时还不影响之前的使用
> > 
> > 
> > 嗯嗯，大佬我已经手动添加上，并且使用大佬您的配置成功解锁网易云了，速度也很快！~但是经过我测试，发现大佬您的4个网易云解锁节点，1和4是可用的，2和3不可用，可能是2和3解锁节点失效了，不过不影响使用，还是万分感谢大佬！~最后还有一个问题想问下大佬，如果我直接使用您的qx配置文件，我应该就自己再不用生成证书了吧，直接点配置证书，配置好您的证书并信任是否就可以了？
> 
> 节点2我刚试了下是有用的，为什么你那里没用我不太清楚，是不是没有信任解锁网易云音乐的证书呢？，3比较慢而且时常抽风。另外，如果你有一套自己的quanx的配置，不建议用quanx方式一的全局配置文件，因为这个配置只有广告屏蔽和解锁网易云音乐的分流策略，当然，如果你自己在这个基础上另外加也可以。至于quanx中mitm的证书，你也可以用全局配置中的那个证书，信任后就可以了。如果担心隐私和安全问题，你也可以在quanx中另外生成一个。

大佬我刚再测试了下，发现节点2确实是可以用的，歌是解锁可以听的，证书我一直是保持信任状态的。我之前是用节点2，看到歌曲下方还有vip那红字，就以为没解锁成功，是我测试失误哈。至于mitm证书，我想问下大佬如果用了别人的配置，配置里面带着别人的证书，我该怎么操作可以把它换成自己生成的证书呢？自己点击生成证书，qx会提示配件文件已存在有效的证书信息，无需重新生成。

**Comment by LOLICOL1** [comment]
> @miracle1103
> 
> 
> 
> 
> > > @miracle1103
> > > > > @miracle1103
> > > > > > > @miracle1103
> > > > > > > 大佬我直接用了你的配置，发现网易云是成功解锁了，但是发现fq节点用不了了，是怎么回事啊？
> > > > > > 
> > > > > > 
> > > > > > 如果你是直接导入了配置文件，那么相当于用了一个新的配置，而这个配置是没有科学上网的节点的，所以也就不存说可以fq了，如果你用的是clash并且能折腾可以去用转换api自己写分流然后合并两个订阅，如果不能，那就在不听网易时换回平时的配置，如果用的其他代理软件，比较好添加节点订阅和分流订阅，也可以手动添加节点和分流订阅。
> > > > > 
> > > > > 
> > > > > 嗯嗯，谢谢大佬解惑！我用的iphone的quantumultx代理工具，我是有从机场购买的节点订阅的，不能fq可能是因为我没有设置策略组分流，也没有添加远程的分流订阅，所以肯定是不能科学上网了。感谢大佬热心解答！~
> > > > 
> > > > 
> > > > 用quanx可以参考文中iOS部分[quanx手动修改配置](https://lolico.me/2020/03/23/unblock-netease-music/#QuantumultX)这部分内容，自行修改配置，在自己原有配置的基础上再在对应板块添加给出的配置就可以做到解锁的同时还不影响之前的使用
> > > 
> > > 
> > > 嗯嗯，大佬我已经手动添加上，并且使用大佬您的配置成功解锁网易云了，速度也很快！~但是经过我测试，发现大佬您的4个网易云解锁节点，1和4是可用的，2和3不可用，可能是2和3解锁节点失效了，不过不影响使用，还是万分感谢大佬！~最后还有一个问题想问下大佬，如果我直接使用您的qx配置文件，我应该就自己再不用生成证书了吧，直接点配置证书，配置好您的证书并信任是否就可以了？
> > 
> > 节点2我刚试了下是有用的，为什么你那里没用我不太清楚，是不是没有信任解锁网易云音乐的证书呢？，3比较慢而且时常抽风。另外，如果你有一套自己的quanx的配置，不建议用quanx方式一的全局配置文件，因为这个配置只有广告屏蔽和解锁网易云音乐的分流策略，当然，如果你自己在这个基础上另外加也可以。至于quanx中mitm的证书，你也可以用全局配置中的那个证书，信任后就可以了。如果担心隐私和安全问题，你也可以在quanx中另外生成一个。
> 
> 大佬我刚再测试了下，发现节点2确实是可以用的，歌是解锁可以听的，证书我一直是保持信任状态的。我之前是用节点2，看到歌曲下方还有vip那红字，就以为没解锁成功，是我测试失误哈。至于mitm证书，我想问下大佬如果用了别人的配置，配置里面带着别人的证书，我该怎么操作可以把它换成自己生成的证书呢？自己点击生成证书，qx会提示配件文件已存在有效的证书信息，无需重新生成。
> 
> 

把mitm下面p12的内容删掉就可以重新生成了，生成新的证书并且安装信任之后建议把之前信任的证书删了

**Comment by miracle1103** [comment]
> > @miracle1103
> > > > @miracle1103
> > > > > > @miracle1103
> > > > > > > > @miracle1103
> > > > > > > > 大佬我直接用了你的配置，发现网易云是成功解锁了，但是发现fq节点用不了了，是怎么回事啊？
> > > > > > > 
> > > > > > > 
> > > > > > > 如果你是直接导入了配置文件，那么相当于用了一个新的配置，而这个配置是没有科学上网的节点的，所以也就不存说可以fq了，如果你用的是clash并且能折腾可以去用转换api自己写分流然后合并两个订阅，如果不能，那就在不听网易时换回平时的配置，如果用的其他代理软件，比较好添加节点订阅和分流订阅，也可以手动添加节点和分流订阅。
> > > > > > 
> > > > > > 
> > > > > > 嗯嗯，谢谢大佬解惑！我用的iphone的quantumultx代理工具，我是有从机场购买的节点订阅的，不能fq可能是因为我没有设置策略组分流，也没有添加远程的分流订阅，所以肯定是不能科学上网了。感谢大佬热心解答！~
> > > > > 
> > > > > 
> > > > > 用quanx可以参考文中iOS部分[quanx手动修改配置](https://lolico.me/2020/03/23/unblock-netease-music/#QuantumultX)这部分内容，自行修改配置，在自己原有配置的基础上再在对应板块添加给出的配置就可以做到解锁的同时还不影响之前的使用
> > > > 
> > > > 
> > > > 嗯嗯，大佬我已经手动添加上，并且使用大佬您的配置成功解锁网易云了，速度也很快！~但是经过我测试，发现大佬您的4个网易云解锁节点，1和4是可用的，2和3不可用，可能是2和3解锁节点失效了，不过不影响使用，还是万分感谢大佬！~最后还有一个问题想问下大佬，如果我直接使用您的qx配置文件，我应该就自己再不用生成证书了吧，直接点配置证书，配置好您的证书并信任是否就可以了？
> > > 
> > > 
> > > 节点2我刚试了下是有用的，为什么你那里没用我不太清楚，是不是没有信任解锁网易云音乐的证书呢？，3比较慢而且时常抽风。另外，如果你有一套自己的quanx的配置，不建议用quanx方式一的全局配置文件，因为这个配置只有广告屏蔽和解锁网易云音乐的分流策略，当然，如果你自己在这个基础上另外加也可以。至于quanx中mitm的证书，你也可以用全局配置中的那个证书，信任后就可以了。如果担心隐私和安全问题，你也可以在quanx中另外生成一个。
> > 
> > 
> > 大佬我刚再测试了下，发现节点2确实是可以用的，歌是解锁可以听的，证书我一直是保持信任状态的。我之前是用节点2，看到歌曲下方还有vip那红字，就以为没解锁成功，是我测试失误哈。至于mitm证书，我想问下大佬如果用了别人的配置，配置里面带着别人的证书，我该怎么操作可以把它换成自己生成的证书呢？自己点击生成证书，qx会提示配件文件已存在有效的证书信息，无需重新生成。
> 
> 把mitm下面p12的内容删掉就可以重新生成了，生成新的证书并且安装信任之后建议把之前信任的证书删了

嗯嗯，照着大佬提示的操作步骤，成功生成安装了自己的证书，并把之前信任的证书给移除掉了。万分感谢大佬的耐心指导！~向大佬您学习和致敬！~

**Comment by coxcaifa** [comment]
感谢大佬，海外党非常需要，已支持6.6买瓶可乐吧

**Comment by LOLICOL1** [comment]
> @coxcaifa
> 感谢大佬，海外党非常需要，已支持6.6买瓶可乐吧

哈哈，能用上就好，感谢投食～

**Comment by Cleo11** [comment]
电脑上的🆗了，但手机用quantumult x显示解锁节点2错误是怎么回事？

**Comment by LOLICOL1** [comment]
> @Cleo11
> 电脑上的🆗了，但手机用quantumult x显示解锁节点2错误是怎么回事？

qx进其他设置，看一下底部的验证是不是一个问号

**Comment by LOLICOL1** [comment]
> @Cleo11
> 电脑上的🆗了，但手机用quantumult x显示解锁节点2错误是怎么回事？

如果底部是一个问号，那就商店登陆一下购买qx的id后进入qx的其他设置再验证一次，变成绿色的√后就可以了。

**Comment by pxf123** [comment]
Clash for Windows v0.8.10 添加订阅，更新之后，proxies > rule下是空白的
是不支持还是版本问题（Clash for Android 可以看到代理规则，用的同一个订阅链接，应该是没问题的，别的订阅链接可以，就网易云的不行，试了两个，比较奇怪（＞人＜；），所以想问问）

**Comment by LOLICOL1** [comment]
> @pxf123
> Clash for Windows v0.8.10 添加订阅，更新之后，proxies > rule下是空白的
> 是不支持还是版本问题（Clash for Android 可以看到代理规则，用的同一个订阅链接，应该是没问题的，别的订阅链接可以，就网易云的不行，试了两个，比较奇怪（＞人＜；），所以想问问）

v0.8.10版本的确不支持，因为clash在0.9.8（好像是这个版本）改变了配置文件一些地方的写法，导致节点显示不出来，实际上是在配置文件里的。

**Comment by miracle1103** [comment]
大佬，现在网易云音乐的解锁节点是都是失效了吗？

**Comment by LOLICOL1** [comment]
> @miracle1103
> 大佬，现在网易云音乐的解锁节点是都是失效了吗？

没失效啊，可用

**Comment by wanhzin** [comment]
感谢🙏分享谢谢大佬

**Comment by chuntsky** [comment]
感谢分享，有用！

**Comment by nightsnack** [comment]
mac需要先安装CA证书，麻烦博主加一下备注

**Comment by heeroyuyj** [comment]
幸好有国外的基友, 借了个号出去下载 shadowrockets

**Comment by heeroyuyj** [comment]
话说我有 windows 下的客户端程序, 它也支持局域网代理啥的, 但是我把 IP 和端口号填到 shadowrockets 里, 套用你的规则, 播放歌曲, 对于灰色的歌曲播放就是提示网络不给力无法播放或者无法解析之类的错误, ca 证书我是有装的, 但是好像只适用于 pac 那种代理或者你的代理节点, 要如何才能利用我自己的代理客户端呢

**Comment by wutea7** [comment]
> @heeroyuyj
> 话说我有 windows 下的客户端程序, 它也支持局域网代理啥的, 但是我把 IP 和端口号填到 shadowrockets 里, 套用你的规则, 播放歌曲, 对于灰色的歌曲播放就是提示网络不给力无法播放或者无法解析之类的错误, ca 证书我是有装的, 但是好像只适用于 pac 那种代理或者你的代理节点, 要如何才能利用我自己的代理客户端呢

同问啊。我在海外服务器上配置好了之后，win客户端是可用的，ios的wifi感叹号代理也是可用的，但是放到 shadowrocket 上就不行了，试了好几套规则包括博主的规则都不行，但是用博主的服务器和博主的规则是完全没问题的，不知道问题出在哪了。博主要不要考虑一下写个教程救救孩子们，呜呜

**Comment by GavinXcXc** [comment]
建议默认开启tap模式

**Comment by GavinXcXc** [comment]
> 建议默认开启tap模式

我这边网络环境默认存在代理（公司默认FQ），直接开启代理，会出现google等无法访问的情况

我尝试在dns前增加  mimix，就都正常了

**Comment by start0325** [comment]
感谢长期分享！提醒一下，需要修改代码 https://github.com/nondanee/UnblockNeteaseMusic/issues/737#issuecomment-826024311

**Comment by LOLICOL1** [comment]
> @start0325
> 感谢长期分享！提醒一下，需要修改代码 https://github.com/nondanee/UnblockNeteaseMusic/issues/737#issuecomment-826024311

已更新

**Comment by inbogota** [comment]
大佬大佬，shadowrocket更新了，可以把网易云的规则自动合并进科学分流规则啦，有没有什么办法可以在vps上搭建网易云的server端，把科学和音乐结合一下下呢，这样在外面就可以不用俩配置之间切换了 （懒就是生产力，逃
Google了好久，也没有这方面的思路……

**Comment by beer-on-ice** [comment]
大佬节点3怎么搭建的，docker还是直接拉代码node跑的，目前我这就节点3能用，自建的会网络不给力

**Comment by LOLICOL1** [comment]
> 大佬节点3怎么搭建的，docker还是直接拉代码node跑的，目前我这就节点3能用，自建的会网络不给力

节点3不是拉docker跑的。其他节点并不是我搭建的，网络上搜集的。最近酷我更新会导致代理端解析不了响应，如果代理端没更新就可能会失效。

**Comment by LOLICOL1** [comment]
> 大佬大佬，shadowrocket更新了，可以把网易云的规则自动合并进科学分流规则啦，有没有什么办法可以在vps上搭建网易云的server端，把科学和音乐结合一下下呢，这样在外面就可以不用俩配置之间切换了 （懒就是生产力，逃
> Google了好久，也没有这方面的思路……

服务端不需要分流，可以在客户端进行分流，根据不同请求代理到不同的节点，目前有很多第三方订阅转换工具可以合并订阅并自定义分流规则。shadowrocket貌似不能定义策略组，也就导致分流规则不能指定某个特定的组，只能选择Proxy，也就是手动选定的节点。clash和qx是支持定义分组的

**Comment by inbogota** [comment]
> @LOLICOL1
> > 大佬大佬，shadowrocket更新了，可以把网易云的规则自动合并进科学分流规则啦，有没有什么办法可以在vps上搭建网易云的server端，把科学和音乐结合一下下呢，这样在外面就可以不用俩配置之间切换了 （懒就是生产力，逃
> > Google了好久，也没有这方面的思路……
> 
> 服务端不需要分流，可以在客户端进行分流，根据不同请求代理到不同的节点，目前有很多第三方订阅转换工具可以合并订阅并自定义分流规则。shadowrocket貌似不能定义策略组，也就导致分流规则不能指定某个特定的组，只能选择Proxy，也就是手动选定的节点。clash和qx是支持定义分组的

是的，shadowrocket没有这个功能，所以才设想在服务端既搭建科学，又搭建音乐，然后在科学的分流配置里添加网易云规则，这样可以同时达到两者效果。但后来查了一下，解锁云音乐搭建在境外的vps上，会因为版权问题不能用，遂作罢
另：大佬能不能更新下证书，实测在我的op的云解锁下，nondanee的证书已经没法用了。玩软路由的小伙伴也都陆续反馈，nondanee的证书即将过期。
可是尝试换成 https://github.com/immortalwrt/packages/commit/c2be6e46fa9b321caa8a22f4090ae97efe414fd4

**Comment by LOLICOL1** [comment]
> > @LOLICOL1
> > > 大佬大佬，shadowrocket更新了，可以把网易云的规则自动合并进科学分流规则啦，有没有什么办法可以在vps上搭建网易云的server端，把科学和音乐结合一下下呢，这样在外面就可以不用俩配置之间切换了 （懒就是生产力，逃
> > > Google了好久，也没有这方面的思路……
> > 
> > 服务端不需要分流，可以在客户端进行分流，根据不同请求代理到不同的节点，目前有很多第三方订阅转换工具可以合并订阅并自定义分流规则。shadowrocket貌似不能定义策略组，也就导致分流规则不能指定某个特定的组，只能选择Proxy，也就是手动选定的节点。clash和qx是支持定义分组的
> 
> 是的，shadowrocket没有这个功能，所以才设想在服务端既搭建科学，又搭建音乐，然后在科学的分流配置里添加网易云规则，这样可以同时达到两者效果。但后来查了一下，解锁云音乐搭建在境外的vps上，会因为版权问题不能用，遂作罢
> 另：大佬能不能更新下证书，实测在我的op的云解锁下，nondanee的证书已经没法用了。玩软路由的小伙伴也都陆续反馈，nondanee的证书即将过期。
> 可是尝试换成 https://github.com/immortalwrt/packages/commit/c2be6e46fa9b321caa8a22f4090ae97efe414fd4

证书我看了下是2024年过期呀，而且订阅里的节点并不全是我搭建的，节点三才是我搭建的，而且其实节点三并不需要信任私有证书

**Comment by xiaoxiongzi** [comment]
大佬，我的服务已经搭建好了：http://106.55.247.237:2333/proxy.pac
然后clash.yaml 配置文件如下：
```yaml
port: 7890
socks-port: 7891
allow-lan: false
mode: Rule
log-level: info
external-controller: :9090
dns:
  enable: true
  listen: 0.0.0.0:53
  enhanced-mode: fake-ip
  nameserver:
    - 119.29.29.29
    - 223.5.5.5
    - 114.114.114.114

proxies:
  - name: "🎸 网易云音乐"
    type: http
    server: 106.55.247.237
    port: 2333

proxy-groups:
  - name: "NeteaseMusic"
    type: select
    proxies:
      - "🎸 网易云音乐"
      - "DIRECT"  

rules:
  - DOMAIN,music.163.com,🎸 网易云音乐
  - DOMAIN,api.iplay.163.com,🎸 网易云音乐
  - DOMAIN,apm.music.163.com,🎸 网易云音乐
  - DOMAIN,apm3.music.163.com,🎸 网易云音乐
  - DOMAIN,interface.music.163.com,🎸 网易云音乐
  - DOMAIN,interface3.music.163.com,🎸 网易云音乐
  - IP-CIDR,39.105.63.80/32,🎸 网易云音乐,no-resolve
  - IP-CIDR,45.254.48.1/32,🎸 网易云音乐,no-resolve
  - IP-CIDR,47.100.127.239/32,🎸 网易云音乐,no-resolve
  - IP-CIDR,59.111.160.195/32,🎸 网易云音乐,no-resolve
  - IP-CIDR,59.111.160.197/32,🎸 网易云音乐,no-resolve
  - IP-CIDR,59.111.181.35/32,🎸 网易云音乐,no-resolve
  - IP-CIDR,59.111.181.38/32,🎸 网易云音乐,no-resolve
  - IP-CIDR,59.111.181.60/32,🎸 网易云音乐,no-resolve
  - IP-CIDR,101.71.154.241/32,🎸 网易云音乐,no-resolve
  - IP-CIDR,103.126.92.132/32,🎸 网易云音乐,no-resolve
  - IP-CIDR,103.126.92.133/32,🎸 网易云音乐,no-resolve
  - IP-CIDR,112.13.119.17/32,🎸 网易云音乐,no-resolve
  - IP-CIDR,112.13.122.1/32,🎸 网易云音乐,no-resolve
  - IP-CIDR,115.236.118.33/32,🎸 网易云音乐,no-resolve
  - IP-CIDR,115.236.121.1/32,🎸 网易云音乐,no-resolve
  - IP-CIDR,118.24.63.156/32,🎸 网易云音乐,no-resolve
  - IP-CIDR,193.112.159.225/32,🎸 网易云音乐,no-resolve
  - IP-CIDR,223.252.199.66/32,🎸 网易云音乐,no-resolve
  - IP-CIDR,223.252.199.67/32,🎸 网易云音乐,no-resolve

  - DOMAIN,admusicpic.music.126.net,REJECT
  - DOMAIN,iadmat.nosdn.127.net,REJECT
  - DOMAIN,iadmusicmat.music.126.net,REJECT
  - DOMAIN,iadmusicmatvideo.music.126.net,REJECT

  - MATCH,DIRECT
```
配置文件的网址如下：https://image-1253705413.cos.ap-guangzhou.myqcloud.com/unblockNeteaseMusic.yaml
但是在安卓的clash软件中导入这份配置文件时，发现配置文件并没有生效。请问我这份配置文件有什么问题吗？
